# Generated by Django 5.1.2 on 2025-02-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('ingredientes', models.TextField()),
                ('modo_preparo', models.TextField()),
                ('tempo_preparo', models.IntegerField()),
                ('porcoes', models.IntegerField()),
                ('categoria', models.CharField(max_length=100)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='receitas/')),
            ],
        ),
    ]
