# Generated by Django 5.1.2 on 2025-02-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='imagem',
        ),
        migrations.AddField(
            model_name='receita',
            name='imagem_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
